# pnpm-workspace.yml
# We use pnpm to configures multi-package workspace project.
# This file lists all packages in project
# Author: Ke An Nguyen
packages:
  - 'packages/backend'   # Package contains backend code
  - 'packages/frontend'  # Package contains frontend code