# docker-compose-prod.yml
# This file lists the containers running the services to be run on production:
# - app-backend-prod: Runs backend process
# - nginx-reverse-proxy-prod: reverse proxy forwarding the /api prefix request
#   to backend process or serves the static-built frontend files (frontend served by reverse proxy)
#   for all other requests.
# Author: Ke An Nguyen
version: '1.29.2'

services:
  app-backend-prod:
    container_name: app-backend-prod
    build:
      context: ..
      dockerfile_inline: |
        FROM  node:18-alpine3.16
        RUN npm install -g pnpm
    volumes:
       - "${ROOT_PROJECT}:${ROOT_PROJECT}:Z"
    command: sh -c "cd ${ROOT_PROJECT} && ${DOCKER_PROD_ENTRY_CMD}"
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    user: "${DOCKER_UID}:${DOCKER_UID}"