# docker-compose.staging.yml
# This docker compose sets up the services required in staging environment.
# Specifically, it mimics the production environment by building pictures-for-docs frontend
# file and make nginx serve it, the backend is running without hot reloading
# Author: Ke An Nguyen

services:
  shop-monorepo-app-staging:
    container_name: shop-monorepo-app-staging
    build:
      context: ..
      dockerfile_inline: |
        FROM  node:22-slim
        RUN npm install -g pnpm
        RUN apt-get update && apt-get install -y --no-install-recommends \
                    openssl \
                    zlib1g \
                    libgcc-s1 \
                    libc6 \
                    && apt-get clean && rm -rf /var/lib/apt/lists/*
    volumes:
      - "${ROOT_PROJECT}:${ROOT_PROJECT}:Z"
    command: sh -c "cd ${ROOT_PROJECT} && ${DOCKER_STAGING_ENTRY_CMD}"
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    user: "${DOCKER_UID}:${DOCKER_GID}"
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:17.2
    container_name: postgres-db
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    env_file:
      - "../../.env"
    volumes:
      - postgres_data_staging:/var/lib/postgresql/data

  shop-monorepo-nginx-staging:
    container_name: shop-monorepo-nginx-staging
    image: nginx:alpine
    volumes:
      - "${ROOT_PROJECT}/packages/frontend/dist:/var/www/html"
      - "${NGINX_STAGING}:/etc/nginx/conf.d/nginx-staging.conf:Z"
      - "${TLS_DIR}:/etc/nginx/certs"
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - shop-monorepo-app-staging

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    volumes:
      - "${MINIO}:/data:Z"
    env_file:
      - "../../.env"
    command: server /data

volumes:
  postgres_data_staging: