# docker-compose-prod.yml
# This docker compose sets up the service required in production environment.
# Specifically, the frontend file is built to static file and served by nginx,
# the database is not in container anymore but will be defined in .env file
# in production server (my OVH server)
# Author: Ke An Nguyen

services:
  shop-monorepo-app-prod:
    container_name: shop-monorepo-app-prod
    build:
      context: ..
      dockerfile_inline: |
        FROM  node:22-slim
        RUN npm install -g pnpm
        RUN apt-get update && apt-get install -y --no-install-recommends \
                    openssl \
                    zlib1g \
                    libgcc-s1 \
                    libc6 \
                    && apt-get clean && rm -rf /var/lib/apt/lists/*
    volumes:
       - "${ROOT_PROJECT}:${ROOT_PROJECT}:Z"
    command: sh -c "cd ${ROOT_PROJECT} && ${DOCKER_PROD_ENTRY_CMD}"
    environment:
      - NODE_ENV=production
    ports:
      - "8080:8080"
    user: "${DOCKER_UID}:${DOCKER_UID}"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
    volumes:
      - "${MINIO}:/data:Z"
    env_file:
      - "../../.env"
    command: server /data