version: '3.8'

services:
  app-dev:
    container_name: ${APP_DEV_CONTAINER}
    image: node:18.18-alpine
    volumes:
      - "${ROOT_PROJECT}:${ROOT_PROJECT}:Z"

    command: sh -c "cd ${ROOT_PROJECT} && ${DOCKER_APP_CMD}"
    ports:
      - "3000:3000"
      - "8080:8080"
    user: "${DOCKER_UID}:${DOCKER_UID}"
    privileged: true

  nginx-reverse-proxy-dev:
    container_name: ${NGINX_REVERSE_PROXY_DEV_CONTAINER}
    image: nginx:alpine
    volumes:
      - "${ROOT_PROJECT}/scripts/nginx/nginx-dev.conf:/etc/nginx/conf.d/nginx-dev.conf:Z"
      - "${ROOT_PROJECT}/scripts/tls-dev:/etc/nginx/certs"
    ports:
     - "443:443"
     - "80:80"
    depends_on:
      - app-dev