version: '3.8'

services:
  app-backend-prod:
    container_name: ${BACKEND_PROD_CONTAINER}
    build:
      context: "${ROOT_PROJECT}"
      dockerfile: "${ROOT_PROJECT}/scripts/Dockerfile"
    ports:
      - "8080:8080"
    user: "${DOCKER_UID}:${DOCKER_UID}"

  nginx-reverse-proxy-prod:
    container_name: ${NGINX_REVERSE_PROXY_PROD_CONTAINER}
    image: nginx:alpine
    volumes:
      - "${ROOT_PROJECT}/packages/frontend/dist:/var/www/html"
      - "${ROOT_PROJECT}/scripts/nginx/nginx-prod.conf:/etc/nginx/conf.d/nginx-prod.conf:Z"
      - "${ROOT_PROJECT}/scripts/tls-dev:/etc/nginx/certs"
    ports:
     - "443:443"
     - "80:80"
    depends_on:
      - app-backend-prod
