name: Auto deploy prod to VPS pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production # Specify environment that holds the secrets used in this pipeline

    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/ssh_vps_private.key
          chmod 600 ~/.ssh/ssh_vps_private.key
          cat >>~/.ssh/config <<END
          Host VPS_SERVER
            HostName $SSH_HOST
            User $SSH_USER
            Port $SSH_PORT
            IdentityFile ~/.ssh/ssh_vps_private.key
            StrictHostKeyChecking no
          END
        env:
          SSH_HOST: ${{ secrets.VPS_SSH_HOST }}
          SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          SSH_PORT: ${{ secrets.VPS_SSH_PORT }}
          SSH_USER: ${{ secrets.VPS_SSH_USER }}

      - name: SSH into server and sync the source code
        run: |
          ssh VPS_SERVER << EOF
            eval "$(ssh-agent -s)"
            ssh-add ~/.ssh/github
            ssh-add -l
            cd ~/Official-Fullstack-Skeleton
            git reset --hard
            git clean -fd
            git pull origin main
          EOF

      - name: Start backend process, build frontend files for Nginx (pre-configured reverse proxy on my server)
        run: |
          ssh VPS_SERVER << EOF
            cd ~/Official-Fullstack-Skeleton
            yes | ./infrastructure/entrypoint.sh prod
            sudo cp -a packages/frontend/dist/. /var/www/html/ofs/
          EOF

      - name: Restart Nginx
        run: ssh VPS_SERVER 'sudo systemctl restart nginx.service'
